---
abstract: 'Ultra special pretty cute diff generator Mark II'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4001, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Difflet
no_index:
  directory:
    - inc
provides:
  Data::Difflet:
    file: lib/Data/Difflet.pm
    version: 0.04
  Test::Difflet:
    file: lib/Test/Difflet.pm
    version: 0
requires:
  Term::ANSIColor: 0
  Test::More: 0.96
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
