---
abstract: 'Ultra special pretty cute diff generator Mark II'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF@ GMAIL COM>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.2, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Difflet
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Data::Difflet:
    file: lib/Data/Difflet.pm
    version: 0.07
  Test::Difflet:
    file: lib/Test/Difflet.pm
    version: 0
requires:
  Term::ANSIColor: 0
  Test::More: 0.96
  parent: 0
  perl: 5.008008
resources:
  bugtracker: https://github.com/tokuhirom/Data-Difflet/issues
  homepage: https://github.com/tokuhirom/Data-Difflet
  repository: git://github.com/tokuhirom/Data-Difflet.git
version: 0.07
x_contributors:
  - 'Syohei YOSHIDA <syohex@gmail.com>'
  - 'Olaf Alders <olaf@wundersolutions.com>'
  - 'Kozaki, Tsuneaki <kozaki.tsuneaki@gmail.com>'
  - 'tokuhirom <tokuhirom@gmail.com>'
